replicaCount: 1
revisionHistoryLimit: 3

image:
  repository: 975050251584.dkr.ecr.ap-northeast-2.amazonaws.com/dev/reserve-api
  tag: 060aa16c6b43479abfeeb7deadb4a5dc0526514e
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80
  targetPort: 8081

namespace: dev

resources:
  limits:
    cpu: 100m
    memory: 200Mi
  requests:
    cpu: 50m
    memory: 100Mi
