replicaCount: 1
revisionHistoryLimit: 3

image:
  repository: 975050251584.dkr.ecr.ap-northeast-2.amazonaws.com/dev/reserve-api
  tag: 3c5cac4e243d6b977c5fd56974f87ab1533a7e6b
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80
  targetPort: 8081

namespace: dev

resources:
  limits:
    cpu: 100m
    memory: 200Mi
  requests:
    cpu: 50m
    memory: 100Mi
