replicaCount: 1
revisionHistoryLimit: 3

image:
  repository: 975050251584.dkr.ecr.ap-northeast-2.amazonaws.com/dev/reserve-api
  tag: f224680a1f74ce4a1c44a8fba264f261bcc4125e
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80
  targetPort: 8081

namespace: dev

resources:
  limits:
    cpu: 100m
    memory: 200Mi
  requests:
    cpu: 50m
    memory: 100Mi
